name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  unit-test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install PNPM
      run: npm install -g pnpm

    - name: Cache node modules
      id: cache-pnpm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # pnpm cache files are stored in `~/.pnpm` on Linux/macOS
        path: ~/.pnpm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-pnpm.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: pnpm list

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm run test:headless

    - name: Build
      run: pnpm run build

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN_GITHUB_ACTION }}
        publish_dir: dist/to-do-list
        publish_branch: gh-pages
        enable_jekyll: true